### ISSUE TITLE
Remove spaces to Calc declarations

### ISSUE THREAD

**Issue by flaprimo** [jakubpawlowicz/clean-css#496]
Hi,
I'm using gulp with the gulp-minify-css plugin (https://www.npmjs.com/package/gulp-minify-css, which uses clean-css).
The tool removes the space after the ")" parenthesis changing the meaning of the following css declarations:

`width: calc((978px * 2/3) - 30px);` to `width: calc((978px * 2/3)- 30px);`

and

`width: calc((978px / 3) - 30px);` to `width: calc((978px / 3)- 30px);`

**Comment by jakubpawlowicz** [comment]
That's a bug indeed. Fix is coming!

**Comment by flaprimo** [comment]
Thank you!
Really appreciate your efforts and this useful software!

**Comment by jakubpawlowicz** [comment]
Fixed in 3.1.7.

**Comment by zackcote** [comment]
Still experiencing this issue in 3.1.8, although looking at the source I can't see why: https://github.com/jakubpawlowicz/clean-css/blob/master/lib/selectors/optimizers/simple.js#L181

The snippet in question: ` left: calc(99.99% * 1/3 - (30px - 30px * 1/3)+ 30px);`
