### ISSUE TITLE
IE hack issue

### ISSUE THREAD

**Issue by thekondrashov** [jakubpawlowicz/clean-css#595]
I tried to use [IE 10 css hack](http://browserstrangeness.bitbucket.org/css_hacks.html) by Jeff Clayton:
```css
/* only works in IE 10 */
_:-ms-lang(x), .selector { property:value\9; }
```
My real input CSS:
```css
/* IE 10 special css */
_:-ms-lang(x), @-ms-viewport {
  width: auto\9 !important;
}
```
Expected output:
```css
_:-ms-lang(x),@-ms-viewport{width:auto\9!important}
```
But real output is empty.

I use clean-css through `Minify` package for Sublime Text (it uses clean-css directly).
Command line parameters: `--s0 -s --skip-rebase`
Latest version of clean-css (now is v3.3.1) on Windows 8.1 Pro x64.

**Comment by jakubpawlowicz** [comment]
@thekondrashov it seems to be lost somewhere during parsing process

**Comment by vdclouis** [comment]
`outline: thin dotted \9; /* IE6-9 */`
get's parsed as 
`outline: thing dotted;`

**Comment by cvillanujr** [comment]
I'm having the same issue, but in my case it's completely removing the line. I'm using this in my grunt build.
```
cssmin: {
  build: {
    options: {
      compatibility: '*,-properties.ieSuffixHack'
    },
    files: {
      'assets/styles/global.css': 'assets/styles/global.cs'
    }
  }
}
```

```
input {
background: #fff;
line-height: 1 \9;
}
```
outputs:
```
input {
background: #fff;
}
```

**Comment by jakubpawlowicz** [comment]
Seems like two different bugs, one with selector parsing, the other with value parsing. Stay tuned, fix is coming.

**Comment by cvillanujr** [comment]
Thank you.

**Comment by jakubpawlowicz** [comment]
Fixed in 3.3.2.

**Comment by cvillanujr** [comment]
Gave this another try by updating grunt-contrib-cssmin but no luck. IE9 hacks still getting removed.

**Comment by jakubpawlowicz** [comment]
grunt plugin is apparently still at version 3.1.x - I've opened an issue so it hopefully gets fixed soon: https://github.com/gruntjs/grunt-contrib-cssmin/issues/228

**Comment by cvillanujr** [comment]
Thanks.
