### ISSUE TITLE
[4.0-pre] test failures on Windows

### ISSUE THREAD

**Issue by alexlamsl** [jakubpawlowicz/clean-css#851]
Running locally on Windows I have 14 failures in total.

7 of which is with specifying "hash" object as input sources to `minify()`, which the following seems to workaround them:
```diff
diff --git a/lib/reader/read-sources.js b/lib/reader/read-sources.js
index 1ccbdb2..9c3c2c3 100644
--- a/lib/reader/read-sources.js
+++ b/lib/reader/read-sources.js
@@ -57,7 +57,8 @@ function fromString(input, context, callback) {

 function fromArray(input, context, callback) {
   var inputAsImports = input.reduce(function (accumulator, uri) {
-    accumulator.push(restoreAsRelativeImport(uri));
+    uri = restoreAsRelativeImport(uri);
+    accumulator.push(restoreImport(uri, '') + Marker.SEMICOLON);
     return accumulator;
   }, []);

@@ -71,7 +72,8 @@ function fromHash(input, context, callback) {

   for (uri in input) {
     source = input[uri];
-    inputAsImports.push(restoreAsRelativeImport(uri));
+    uri = restoreAsRelativeImport(uri);
+    inputAsImports.push(restoreImport(uri, '') + Marker.SEMICOLON);

     context.sourcesContent[uri] = source.styles;

@@ -97,17 +99,14 @@ function trackSourceMap(sourceMap, uri, context) {
 function restoreAsRelativeImport(uri) {
   var currentPath = path.resolve('');
   var absoluteUri;
-  var relativeToCurrentPath;

   if (isRemoteResource(uri)) {
-    return restoreImport(uri, '') + Marker.SEMICOLON;
+    return uri;
   } else {
     absoluteUri = isAbsoluteResource(uri) ?
       uri :
       path.resolve(uri);
-    relativeToCurrentPath = path.relative(currentPath, absoluteUri);
-
-    return restoreImport(relativeToCurrentPath, '') + Marker.SEMICOLON;
+    return path.relative(currentPath, absoluteUri);
   }
 }
```

**Comment by jakubpawlowicz** [comment]
Thanks for looking into this. It needs to be green in time of 4.0, but, honestly, I neglected testing it as I go on Windows so far.

**Comment by alexlamsl** [comment]
@jakubpawlowicz I suspected as much, so I thought I could look into this quickly without getting in the way 😛 

Of the remaining 7 tests, 5 are disagreeing between `\n` and `\r\n` with input from strings or fixtures which is `\n` only. The last two are `\` vs `/' in source map paths.

I'm not sure what the expectations are in those cases, so I'm afraid the first patch is all I can do for now...

**Comment by jakubpawlowicz** [comment]
It was actually all due to paths being stored in inconsistent form. Fixed in 909460778f78b7ece96fd2e040cec70b035331e4.

I'll make sure to keep master green on both Windows and *nix from now on.

**Comment by alexlamsl** [comment]
So I'm still getting 5 test failures on Windows 10 and Node.js 7.3.0
```
C:\...\clean-css>npm test

> clean-css@4.0.0-pre test C:\...\clean-css
> vows

 ······························································································································································································································································································································································································································································································································································································ ·················································································· · ············································································································································································································································· ··················································································································································· ······················································································································································ ·············································································································································································································································································································································································································································································································································································································· ········································· ······················································································· ············ ························ ···················· ···························· ························ ···························· ··························· ······ ···················· ······························ ····· ······· ············ ······ ······································ ······································ ········································· ······· ·· ··········· ·············································································· ···························································· ········· ·································································································································································✗··························✗······✗···✗··✗······················ ······················································································ ······ ·········· ··········· ·······················


    inlined sources from array - on
      ✗ has embedded sources content
        » expected [ '.one { color:#f00; }\015\n', '.three {background-image: url(extra/down.gif);}\015\n' ],
        got      [ '.one { color:#f00; }\n', '.three {background-image: url(extra/down.gif);}\n' ] (deepEqual) // C:\...\clean-css\test\source-map-test.js:1360

    inlined sources from source map(s) mixed
      ✗ has embedded sources content
        » expected [ 'div {\n  color: red;\n}\n', 'section {\n  > div a {\n    color:red;\n  }\n}\n', 'div > a {\015\n  color: blue;\015\n}\015\n' ],
        got      [ 'div {\n  color: red;\n}\n', 'section {\n  > div a {\n    color:red;\n  }\n}\n', 'div > a {\n  color: blue;\n}\n' ] (deepEqual) // C:\...\clean-css\test\source-map-test.js:1641

    inlined sources from source map(s) mixed remote and no callback
      ✗ has embedded sources content
        » expected [ null, 'section {\015\n  > div a {\015\n    color:red;\015\n  }\015\n}\015\n', null ],
        got      [ null, 'section {\n  > div a {\n    color:red;\n  }\n}\n', null ] (deepEqual) // C:\...\clean-css\test\source-map-test.js:1806

    inlined sources from source map(s) mixed remote and 404 resource
      ✗ has embedded sources content
        » expected [ null, 'section {\015\n  > div a {\015\n    color:red;\015\n  }\015\n}\015\n', 'div > a {\n  color: blue;\n}\n' ],
        got      [ null, 'section {\n  > div a {\n    color:red;\n  }\n}\n', 'div > a {\n  color: blue;\n}\n' ] (deepEqual) // C:\...\clean-css\test\source-map-test.js:1761

    inlined sources from source map(s) mixed remote
      ✗ has embedded sources content
        » expected [ 'div {\n  color: red;\n}\n', 'section {\015\n  > div a {\015\n    color:red;\015\n  }\015\n}\015\n', 'div > a {\n  color: blue;\n}\n' ],
        got      [ 'div {\n  color: red;\n}\n', 'section {\n  > div a {\n    color:red;\n  }\n}\n', 'div > a {\n  color: blue;\n}\n' ] (deepEqual) // C:\...\clean-css\test\source-map-test.js:1713
  ✗ Broken » 2798 honored ∙ 5 broken (16.798s)
  npm ERR! Test failed.  See above for more details.
```

**Comment by alexlamsl** [comment]
All of them is caused by [this line](https://github.com/jakubpawlowicz/clean-css/blob/master/test/source-map-test.js#L17), where it is defined as `\r\n` whereas the actual output were all `\n`.

**Comment by jakubpawlowicz** [comment]
That's interesting as it works ok on Node.js 4 and 6 - https://ci.appveyor.com/project/jakubpawlowicz/clean-css

I can give it a try on 7 tomorrow.

**Comment by alexlamsl** [comment]
I would try those too except all my Windows boxes have Node 7 on them. :sweat: 

It would be helpful to have CI tests for Node 7 on Linux and Windows anyway.

One possibility may be that `git clone` is "fixing up" line endings of those fixtures files, which I always disable (leave them as-is).

**Comment by jakubpawlowicz** [comment]
Could be the thing about `git clone`, see https://ci.appveyor.com/project/jakubpawlowicz/clean-css/build/690 and https://travis-ci.org/jakubpawlowicz/clean-css/builds/190870717.

Btw, shouldn't we officially support Node.js 4, 6, and 7, given the last one is the current one?

**Comment by alexlamsl** [comment]
@jakubpawlowicz apologies for being unclear - I do mean v7 in addition to v4 & v6.

**Comment by alexlamsl** [comment]
Yeah, just a `git clone` artefact which won't affect any real world use cases then. :+1:

**Comment by jakubpawlowicz** [comment]
Cool! Let's target for v4, v6, and v8 in clean-css 4.
